---
output: word_document
---
```{r include_rticles, include = FALSE}
# This chunk ensures that the rticles package is installed and loaded
# This rticles package includes the template files for the thesis and also
# two functions used for labeling and referencing
if(!require(devtools))
  install.packages("devtools", repos = "http://cran.rstudio.com")
if(!require(rticles)){
  library(devtools)
  devtools::install_github("ismayc/rticles")
  }
library(rticles)
```
---
header-includes:
- \usepackage{graphicx,latexsym}
- \usepackage{amssymb,amsthm,amsmath}
- \usepackage{longtable,booktabs,setspace}
- \usepackage{tikz}
- \usepackage{setspace}
output: pdf_document
---
\onehalfspacing

```{r load_pkgs, message = FALSE, echo=FALSE}
# List of packages required for this analysis
pkg <- c("ape", "klaR","cluster","plyr","dplyr", "ggplot2", "knitr", "devtools")
new.pkg <- pkg[!(pkg %in% installed.packages())]
if (length(new.pkg))
  install.packages(new.pkg, repos = "http://cran.rstudio.com")

# Load packages
library(dplyr)
library(plyr)
library(ggplot2)
library(knitr)
library(cluster)
library(klaR)
library(ape)
```

```{r load_data, cache=TRUE, echo=FALSE, message=FALSE}
setwd("~/Desktop/Thesis/analysis") #remove later
"Load the data from the National Ambulatory Care Survey **insert link**"
NAMCS.work <- read.csv("NAMCS08-11.csv", header = TRUE)
```

```{r load_functions, echo=FALSE, message=FALSE}

create_sample.func <- function (data, n) {
  sample <- sample_n(data, n)
  
  sample
}
probtable.func <- function(variable){
    # get name
    category <- deparse(substitute(variable))
    category <- data.frame(name = category, variable = "", Freq = 100.00, stringsAsFactors = FALSE)
    # get proportions
    table.sums <- table(variable)
    variable.tbl <- round(prop.table(table.sums)*100, 2)
    variable.df <- as.data.frame(variable.tbl, stringsAsFactors = FALSE)
    # add id rows
    variable.df <- cbind(data.frame(name = "", stringsAsFactors = FALSE), variable.df)
    variable.df <- rbind( variable.df[0,0], category, variable.df[] )
    
    variable.df
}
```


```{r clean_data, echo = FALSE, message=FALSE}

urgentCareOnly.df <- subset(NAMCS.work, NAMCS.work$TYPE4CLASS == "Urgent Care Center/Freestanding Clinic")

# fixing NAs/blanks
urgentCareOnly.df[c("VYEAR")][is.na(urgentCareOnly.df[c("VYEAR")])] <- 2011 # 2011's got entered blank
urgentCareOnly.df[urgentCareOnly.df == "Blank"] <- NA
urgentCareOnly.df[urgentCareOnly.df == "Missing Data"] <- NA
urgentCareOnly.df[urgentCareOnly.df == "Missing data"] <- NA

# making (maybe not sure this works*) names shorter for visualization
revalue(urgentCareOnly.df$PCTPOVR, c("Missing data"="Missing",
                               "Quartile 1 (Less than 5.00 percent)"="Q1: <5%", 
                               "Quartile 2 (5.00-9.99 percent)" = "Q2: 5-10%",  
                               "Quartile 3 (10.00-19.99 percent)" = "Q3: 10-20%",
                               "Quartile 4 (20.00 percent or more)" = "Q4: >20%"))
revalue(urgentCareOnly.df$PAYTYPER, c("All sources of payment are blank"="Missing", "Worker's compensation" = "Worker's Comp"))
revalue(urgentCareOnly.df$URBANRUR, c("Micropolitan/noncore (nonmetro)"= "Rural", "Missing data" = "Missing"))

```

```{r define_variable_sets}

continuous.vars <- c("PCTPOVR", "PBAMORER", "URBANRUR", "AGER", "RACER", "SEX", "PAYTYPER")
continuous.varset <- urgentCareOnly.df[continuous.vars]
continuous.varset <- na.omit(continuous.varset)
dim(continuous.varset)

behavioral.vars <- c("URBANRUR","PAYTYPER","INJURY", "PRIMCARE", "SENBEFOR", "PASTVIS", "MAJOR", "WEEKEND")
behavioral.varset <- urgentCareOnly.df[behavioral.vars]
bahavioral.varset <- na.omit(behavioral.vars)
dim(behavioral.varset)

demographic.vars <- c("PCTPOVR", "HINCOMER", "PBAMORER", "URBANRUR", "RACEETH", "WEEKEND", "AGER", "SEX")
demographic.varset <- urgentCareOnly.df[demographic.vars]
demographic.varset <- na.omit(demographic.varset)
dim(demographic.varset)

full.vars <- c("PCTPOVR", "HINCOMER", "PBAMORER", "URBANRUR", "RACER", "WEEKEND", "AGER", "SEX", "URBANRUR","PAYTYPER","INJURY", "PRIMCARE", "SENBEFOR", "PASTVIS", "MAJOR", "WEEKEND")
full.varset <- urgentCareOnly.df[full.vars]
full.varset <- na.omit(full.varset)
dim(full.varset)

```


```{r create_samples}
sample2 <- create_sample.func(full.varset, 300)
sample2 <- na.omit(sample2)
dim(sample2)


sample <- create_sample.func(behavioral.varset, 250)
sample <- na.omit(sample)
dim(sample)

cluster.func <- function (sample) {
  #distance matrix
  summary(sample.dist <- daisy(sample, metric = "gower"))
  sample.dist <- sample.dist^2
  
  # Investigate further z vs h differences
  sample.clust <- hclust(sample.dist, method = "ward.D")
  sample.agnes <- agnes(sample.dist, method = "ward")
  par(mfrow=c(1,1))
  temp <- sample.clust
  temp$height <- sqrt(sample.clust$height)
  plot(temp, labels = FALSE, main="X.hclust -- sqrt(height)")
  plot(sample.agnes, which.plots=2, labels = FALSE, main="X.agnes.wardD2")
  

  # Find number of clusters, need better way
  # sample.heights <- sample.clust$height # height values
  # sample.heights2 <- c( 0, sample.heights[ -length(sample.heights) ])     # finds height values at merge for n obs
  # sample.max <- max(round(sample.heights - sample.heights2, 4))      # finds largest height value
  # optimal <- which.max(round(sample.heights - sample.heights2, 4))   # Determines the location of first 

  sample.clust
  
}

sample2.clust <- cluster.func(sample2)
plot(sample2.clust, labels = FALSE)

sample.clust <- cluster.func(sample)
plot(sample.clust, labels = FALSE)

#cutree(sample.clust, k = 6:18) #k = 1 is trivial
## Compare the 2 and 4 grouping:
#g24 <- cutree(sample.clust, k = c(16,17))
#table(grp2 = g24[,"16"], grp4 = g24[,"17"])

k <- 10
table(cutree(sample.clust, 10))
sample.kmode <- kmodes(sample, modes = k, iter.max = 5)

table(cutree(sample2.clust, 10))
sample2.kmode <- kmodes(sample2, modes = k, iter.max = 5)

Kmodes.func <- function (cluster, k){
  table(cutree(cluster, k))
  sample.kmode <- kmodes(sample, modes = k, iter.max = 10, weighted = FALSE)
}

#table(sample.kmode$modes)
cluster.tbl <- as.data.frame(sample.kmode$modes)
cluster.tbl
cluster.tbl <- cluster.tbl[order(cluster.tbl$PAYTYPER, cluster.tbl$URBANRUR),]

#sample.kmode$modes

cluster.tbl2 <- as.data.frame(sample2.kmode$modes)
cluster.tbl2 <- cluster.tbl2[order(cluster.tbl2$PAYTYPER, cluster.tbl2$URBANRUR),]


#sample.dist2   <- sample.dist^2
#sk2   <- silhouette(sample.kmode$cluster, sample.dist2)
#plot(sk2)

```

```{r try_something_else}

#sample1 <- data.matrix(sample)
#sample1 <- model.matrix(sample1)
library(mclust)
#View(sample)
#d_clust <- Mclust(as.matrix(sample), G=1:20)

```


```{r cluster_tables}

kable(cluster.tbl, col.names = c("Urban/Rural", "Pay Type", "Injury", "Primary Care", "Seen Before", "Past Visits", "Major Reason", "Weekend" ),
      caption = "Clustering Table \\label{tab:clust}", label(scale = .75))


kable(cluster.tbl2, col.names = c("PCTPOVR", "HINCOMER", "PBAMORER", "URBANRUR", "RACEETH", "WEEKEND", "AGER", "SEX", "URBANRUR","PAYTYPER","INJURY", "PRIMCARE", "SENBEFOR", "PASTVIS", "MAJOR", "WEEKEND"),
      caption = "Clustering Table \\label{tab:clust2}", label(scale = .5))

```





```{r logistic model}

model.matrix(demographic.varset)

sapply(demographic.varset,function(x) sum(is.na(x)))

train <- sample_n(behavioral.varset, nrow(behavioral.varset))
test <- behavioral.varset[-train,]

set.seed(666)


glm(NAMCS.work$PRIMCARE ~ NAMCS.work$AGE + NAMCS.work$RACER + NAMCS.work$URBANRUR)

```



