---
header-includes:
- \usepackage{graphicx,latexsym}
- \usepackage{amssymb,amsthm,amsmath}
- \usepackage{longtable,booktabs,setspace}
output: word_document
---
# Analysis
\onehalfspacing

## not rly sure what this section is anymore ....

A quick summary of the data shows that by and large most of the observations continue to choose traditional means of obcuring primary care. Great quote: For our purposes, we do not presume to go quite this far, but we are applying this method as a form of retroduction, using observed evidence to create a research hypothesis that accounts for the observed facts *Sayer, 1992*.

## Identifying Typologies with Clustering
### Differences in Demographic and Behavioral Factors Between Clusters

With cluster assignments established, I analyzed how the identified groups differed from each other in terms of critical demographic chracteristics and behaviors that are described in the literature. Most importantly---in order to better understand the characteristics of individuals choosing to go to urgent care we must understand which chracteristics or bahaviors most distinguished the clusters in the anlaysis. 

Beginning with demographic trends, it is immediatly clear that there are large homogenous groups within the selection of patients who utilize urgent care. Of the 8 clusters, 7 are predominantly or exclusively white.


** cluster tables **

###Differences in Demographic and Behavioral Factors of Urgent Care Seekers

In order to better understand the characteristics of individuals choosing to go to urgent care, we must first understand which characteristics or behaviors most distinguished the clusters in the cluster analysis, and to do this I used the k-modes clustering algorithm to situation observations into similar groups of patients. With cluster assignments established by the hierarchal agglomerative methods above, I then analyzed how the identified groups or 8 and 12 differed from each other in terms of critical demographic characteristics and visit behaviors that were described in the literature review. 

Beginning with demographic trends, the cluster analysis makes immediately clear that there are distinct homogenous groups within the selection of patients who utilize urgent care. Race in particular is immediately noticeable for its lack of variety: of the 12 clusters, 9 are predominantly or exclusively white, an unsurprising trend when one looks at the summary statistics (of the 3863 urgent care visits included in the data, 87% (3352) of those were white individuals). Table 1 shows the modes of each cluster for an illustrative sample of patients, and it is immediately clear that the majority of urgent care goers are white, but that within clusters of white patients there is further segmentation. 

For an example of such segmentation, we can examine the socioeconomic indicators for the patients’ ZIP codes which were included as demographic parameters. Unsurprisingly, these appeared to cluster and correlate with both race and income: for both males and females, there were consistent clusters of White, 25-44-year-old patients with private insurance, and both of these clusters were in the highest quartile of percent population with Bachelor’s degrees, the second lowest percent population under the poverty line (5-10%), and both visited clinics coded as being located in a “Large central metro” (Table 1.). 

In fact, if one predominant trend becomes clear from the demographic clustering, it is that urgent care centers are almost entirely an urban affair. Of the clusters found, all but one consisted of visits located in medium to large metros, indicating that while other variation between patients exists, most urgent care consumers are located in larger cities. And if its singularity wasn’t enough, the cluster of visits which did occur in a rural setting also differed from most other clusters in the other parameters as well. As can be seen in the first row of Table 1., the rural (“Micropolitan/noncore”) cluster of visits had one of the highest levels of localized poverty, one of the lowest levels of educational attainment, and was one of only two clusters where the majority of visits were paid with Medicaid.

**[THIS PARAGRAPH SHOULD OFFER A CLEARER STORY – AND CLARIFY THE DISTINCTION BETWEEN MEDICARE AND MEDICAID]**
Also informative are the clusters’ most occurring payment types, which complicate some of the theoretical notions of urgent care described in Chapter 1. While the largest clusters were consistently comprised of private insurance payers, Medicare without a doubt plays a role in getting people to urgent care centers. Medicaid had the lowest numbers of visits across all trials, averaging around 12 % of the observations. These clusters are crucial to understanding the decision process behind choosing a health care provider, while simultaneously raising the question of the relationship between the surprising number of elderly patients on Medicare seeking treatment at an urgent care centers.

If the demographic clusters illuminate the subgroup characteristics of urgent care seekers with socioeconomic status in mind, the behavioral parameters included in the second wave of cluster analyses allow us to go further in examining how urgent care is utilized by different groups. [READ THAT SENTENCE AND THINK OF YOUR POOR MOTHER.]  

By far the largest and most homogenous clusters isolated consist of white, privately insured patients in medium to large urban environments. These trends match those found in the demographic clusters, and we can learn even more about this group by examining the cluster segmentation that occurred across their behavioral parameters in the second wave. Of the two clusters which consist almost entirely of white, 25-44-year-old men and women (yellow and light pink in Figure 1 above), both were almost entirely classed as “established patients”, with at least one past visit. Also theoretically interesting, neither cluster had observations whose reason for visiting was “injury related” and neither had recorded visits on weekends. Cluster one in particular (Row 1, Table 2), consisted of 25-44-year-old white females with private insurance, an established history of visiting urgent care, and a reason for their current visit coded as a “chronic, routine problem”. [SUGGESTION: LOW-TECH TABLE TO ILLUSTRATE YOUR CLUSTERS. COLUMNS FOR URBAN/RURAL, RACE, AND OTHER KEY VARIABLES.]

In fact, only 32 visits in the example model were coded as new patients (Figure 2, purple and orange), and examining these two clusters reveals what I referred to earlier as the traditional patient characteristics ascribed to urgent care visits. These two cluster show what many would expect, both consisted of white, privately insured, new patients, and both clusters contain the only observations which occurred on a weekend or were coded as injury related.  These characteristics are in line with what many hold as the purpose of urgent care centers, but they remain a small fraction of the recorded number of visits. Completely contradicting this idea, the other seven of the nine clusters identified have high levels of established patients with chronic or routine problems, with ages ranging for 15 to over 75.
	
As for the Medicare question, if the clusters which consist of primarily elderly patients are examined—rows 5 and 9 in Table 2 (Figure 2, magenta and blue)—we can begin to understand a little better the relatively large percentage of what many would consider non-emergent care utilizers and their relationship to urgent care. Cluster 5 consists entirely of white patients between 65 and 74, whose visits were recorded as routine and who have a minimum of 3 past visits at the same center. Cluster nine on the other hand has a slightly older age range of above 75, and visits which were all considered new problems. Also distinguishing, cluster nine is the only cluster with a majority of rural observations. When compared, it appears that there are two typologies of elderly urgent care seekers, the first of which may be using urgent in much the same ways as the younger and larger clusters of privately insured urbanites, while the second seems to rely on urgent care much more as an actually resource for urgent problems. 

### What do these mean?

The question remains how the observed trends align with the literature that assess the ways Americans are accessing healthcare in an increasingly changing market. From the exploratory analysis outlined above, it is possible to use the findings to test the hypotheses outlined in Chapter 1. In doing so, we we compare our set of urgent care visitors to the larger set of observations in the NAMCS that chose traditional means of accessing primary care, testing the parameters which appeared to cluster together within urgent care seekers as possible predictors for urgent care as an outcome (actually, is this something we want to do? I’ve somewhat done this already way back when and most are significant, esp. white, urban, etc. but it might be interesting to take something like chronic routine problem and see what coefficient I get?). 


(working on making aggregated/pretty/readable versions of these)







