---
output: pdf_document
---

<!--
\chapter*{Conclusion}
         \addcontentsline{toc}{chapter}{Conclusion}
	\chaptermark{Conclusion}
	\markboth{Conclusion}{Conclusion}
  \setcounter{chapter}{5}
	\setcounter{section}{0}
	
	Here's a conclusion, demonstrating the use of all that manual incrementing and table of contents adding that has to happen if you use the starred form of the chapter command. The deal is, the chapter command in \LaTeX\ does a lot of things: it increments the chapter counter, it resets the section counter to zero, it puts the name of the chapter into the table of contents and the running headers, and probably some other stuff.
-->

# Conclusion
  \setcounter{chapter}{6}
	\setcounter{section}{0}
  \doublespacing
  
In this thesis, I have attempted to examine the relatively new phenomenon of urgent care centers and their use patterns, reviewing where the sociology of medicine has been and where the American health care system is now. While the analysis was limited by the data availability, the observed groupings of urgent care patients and the significant factors for the decision to use it as urgent care allow us to begin to answer questions about who's going to urgent care and their reasoning. 

With the rapidly increasing amount of data, further research into urgent care centers could benefit from a times series study, in order to answer some of the questions raised about whether or not patient behavior is changing or just dispersing. Additionally, there are an increasing number of health care practices which resemble urgent care, retail clinics located inside large stores being just one example, that could shed further light on the modern patient as a health consumer. 

Lastly, I wonder if there is a way to connect what is sociologically interesting about this topic to broader trends beyond medicine/health care. For example, you tie your narrative very tightly to literature on professionalism. If you extend that theme, is there anything that the replacement of established doctors by a direct care model reveals about other trends like, say, the rise of Massive Open Online Courses (in higher education), the challenge to traditional accountants by institutions like H&R Block and TurboTax, or the decline of professional journalists and the emergence of bloggers? Perhaps this is too random, but if somewhere in your intro or conclusion you can speculate on broader connections about living in an on-demand society where traditional boundaries of expertise and training are increasingly blurred, your study could appeal to a more general audience.

