---
output: word_document
---

# Introduction {.unnumbered}
\onehalfspacing

The days of having a local doctor who cared for all of a patient's health needs are long gone. In their place, a rapidly expanding and complex network of healthcare providers and services have developed, increasingly placing the burden on the patient to make the appropriate choice. In particular, the past twenty years have seen a surge in a new type of medical practice known as urgent care centers, and the industry shows no sign of slowing down. Yet given such rapid expansion of the industry, it is surprising that little academic research has taken urgent care as its subject. In part a response to this oversight, the following analysis will use a representative sample of urgent care center visits to examine the use patterns of these facilities in recent years. I investigate three central questions regarding urgent care: what are the typologies of patients using urgent care, how can we use this information to situate urgent care centers into the larger complex of the American healthcare system, and what does the sociological research offer to an understanding of this relatively new phenomenon? 

There is no official definition of what constitutes an urgent care center, but the scope of services provided generally falls between that of a primary care doctor’s office and an emergency department. The centers typically focus on acute episodic care, and have a substantial emphasis on customer service. Most are open past the hours of a traditional primary care practice, and often have a wider variety of services, such as labs, x-rays and other emergency department equipment [@WEINECK_NOAPPT].

While the industry is currently experiencing rapid growth, the concept got off to a rocky start. The first urgent care centers opened in the United States in the early 1980’s., with no more than a handful in operation at the time.  Unfortunately, (at least as far as early investors were concerned), the industry rapidly declined, and the few clinics which had opened were largely absorbed into larger hospitals and healthcare groups.  Ten years later, in the mid-1990’s , the centers began expanding rapidly, growing to over 12,000 centers today. By the UCAOA’s estimate, in 2014, approximately two new urgent care centers were opening in the United States each week [@UC_10STATS]. 

Such recent and rapid expansion has been heavily examined by the media, which often attribute growth to a diverse set of market factors such as long wait times for primary care appointments, crowded emergency departments and patient demand for more accessible care, including after-hours appointments (Yee, Lechner, and Boukus 2013). Yet despite the rapid development of the industry and the great interest sociologists have historically taken in America’s health care system, hardly any scholarly research has been done on why these centers are coming to play a major part of the healthcare system or what their patterns of use are. While many are quick to point towards long wait times, and the difficulty of finding doctors in the current healthcare system, the repercussions of the new turn towards urgent care centers are not well known, nor has their place in the American healthcare system been examined.  

In the following analysis, I will attempt to situate the rise of such clinics within the existing sociological research on the American healthcare system, the changing face of primary care, and the patients that utilize it, examining hypotheses about how the patterns of use by patients at urgent care centers can help us understand and situate them in to the larger body of medical sociological research. To do this, I draw from theories on the changing relationship between the patient and practitioner to compare three hypotheses of urgent care usage.

In Chapter one, I situate the analysis into the wider body of literature, emphasizing how structural changes in healthcare have generated profound consequences for primary care and modern patients. I begin to place urgent care centers into the context of the US healthcare system's varied actors and organizations, and explore the ways this method of care appears in the literature. In particular, the chapter highlights how these new organizations might informally facilitate the depersonalized relationship between practitioner and patient, eliminating the close ties many historical medical sociologists identified as vital to an optimal doctor patient relationship. Lastly, I identify the current gaps in the literature surrounding new forms of privatized medical care facilities which have been largely overlooked by sociologists and other scholars attempts to understand health care in America. 

Chapter two focuses strictly on urgent care centers themselves, and uses sociological theory to present three plausible explanations of urgent care usage. While the goal is not to generate a predictive model of urgent care, an analysis which tests the three hypotheses by examining sub-groupings of patients who visited urgent care goes far to allowing us to recognize identifiable medical use patterns. Chapter three offers a description of the National Ambulatory Medical Care Survey where I am drawing my analysis from, and includes a description of the methods I use to examine patient visits to urgent care. These include both a k-modal hierarchical clustering exploratory analysis used to identify groups of similar patients who used urgent care and a logistic analysis of those choosing to use urgent care as their primary care facility. Chapters four and five present these analyses, and discuss the findings in light of the research. 

In the conclusion, I explore the implications of the tensions between what is thought important to the doctor-patient relationship, and the reality of accessing healthcare in America today. I argue that primary care, while no longer the traditional town doctor, is still a key gateway for patients, and that urgent care centers may just be a new entry point into the traditional model. I conclude with implications and suggestions for further studies of urgent care and primary care access in America. 

```{r Intro_notes}
# provide more details at the outset about the present state of urgent care center development. Are there any national details about where they tend to be located, how many have professional doctors on sta , if there are networks that link them, etc. A map or a descriptive table early in the thesis would be a good addition.

# If you extend that theme, is there anything that the replacement of established doctors by a direct care model reveals about other trends like, say, the rise of Massive Open Online Courses (in higher education), the challenge to traditional accountants by institutions like H&R Block and TurboTax, or the decline of professional journalists and the emergence of bloggers? Perhaps this is too random, but if somewhere in your intro or conclusion you can speculate on broader connections about living in an on-demand society where traditional boundaries of expertise and training are increasingly blurred, your study could appeal to a more general audience.
#
```
