---
output: word_document
---
# Literature Review {.unnumbered}
\doublespacing

** Need intro to this... make more cohesive **

## Moving away from Primary Care {.unnumbered}

The shift towards urgent care centers will undoubtedly have profound consequences for the patient-practitioner relationship and the patient’s role in the medical care system, but so far these consequences remain largely unknown. Fortunately, sociologists have had a long-standing concern with such professional-client interactions, particularly within medicine (Freidson 1961, Bloom 1963, Mechanic 1968), and in order to better understand what effects the shift away from primary care may have on patients, one can look to a large body of research on how institutional and organizational environments directly affect a patient’s experience in health care.

A major sociological theory of the doctor-patient relationship begins by speculating that the bureaucratization of modern social institutions has had drastic consequences on the medical profession: as opportunities for close personal contacts diminish, problems which were originally handled in familial, social, and religious contexts are transferred to ‘formal sustaining practitioners’ (Mechanic 1966). In such societies, the prescribed structure of the doctor patient relationship then provides a legitimation for the expression of intimacy and the request for help, offering an explanation as to why sociologists and anthropologists of medicine have long observed the variance and social nature of health problems brought to a physician (The Doctor, His Patient, and the Illness). 

These same theorists locate the stability of this doctor-patient relationship in the fact that the physician acts as the patient’s agent, yet one can immediately recognize that urgent care centers may not be equipped to facilitate this relationship in the same way that the traditional primary care practice is seen to (Lupton 1997). The premise of urgency in such practices, the quickness with which patients are seen, and the targeted focus on acute problems all serve to create considerable doubt towards the ability of physicians within such an organizational context to fulfill the sociological role thought so important in previous literature.

Additionally, those who study health services have recognized that a patient’s medical history is a primary source of information regarding treatment, and primary care practitioners have been known to draw upon this as a valuable resource (Draper and Smits 1975; Miller et al. 2010). The Millis report, commissioned by the American Medical Association to review the current status of physicians, recalls the archetype of the medical professional: 

"The general practitioner of revered memory knew his patients… and provided continuing care through the course of minor ailments and majors emergencies. His deficiencies… were partly offset by intimate knowledge of his patients, the support he gave them, and the trust and confidence his services engendered.”

Urgent care centers however have no emphasis on maintaining patient-doctor ties and there is no reliable system to ensure a patient sees the same doctor even if they have been there before.

Yet while this may seem problematic, a large body of recent sociological literature belongs to a growing number of scholars who are challenging the importance, and even relevance, of the traditional primary care physician in modern medicine. Those who have been observing developments in the patient-physician relationship over the past 30 years argue that the last quarter of the 20th century saw a dramatic reconfiguration of society, especially in regards to health services,  which has had profound effects on an individual’s relationship to the healthcare system. So while some were witnessing what was, for Starr (1982), “the social transformation of medicine,” and for many, “the end of the golden age of doctoring” (McKinlay & Marceau 2002). 

###The end of Medical Professional Dominance in the US?{.unnumbered}

Almost since sociologists first became interested in the medical profession, the sociology of medicine was deeply joined with studies of professionalism. In the U.S., Doctors were seen as the paragon of the ‘professional’: respected, organized, in control, and above all else, firmly established in their positions. Such traits led many to study what effects this had on medical care and how such professional dominance of medical practitioners shaped what services were provided. Many found that such dominance allowed the profession to block off areas of study entirely, or to ignore diseases they did not want to pursue. Such “modern doctors” worked within a “sovereign profession” (Starr 1982), serenely dispensing both medical care and authoritative judgment. Freidson (1988, p.384) comments that before 1970’s, U.S. medicine “was at a historically unprecedented peak of prestige, prosperity and political and cultural influence—perhaps as autonomous as it is possible for a profession to be.”
	
When one thinks of the healthcare industry today, it is hard to call to mind such professional cohesion. While doctors remain one of the more highly respected career choices in America, their prestige has certainly dropped since the 20th century (Heritage and Maynard 2006). The term doctor is now applicable to a wide variety of sub-professions and specialties and the medical profession has become extremely diversified. Along with such specialization, big changes to Medicare and Medicaid legislation and the growth of third-party payers and for-profit medical service corporations created conditions which further removed the doctor from their traditional roles, eroding the political and cultural influence of the profession and threatening the cultural authority and technical autonomy of medicine (Starr 1982, Freidson 1988). It should be noted that such changes may not have necessitated a loss of professional dominance. In fact, with the expansive growth on spending in the healthcare sector, it is possible that doctors could have further cemented their professional medical authority. But most scholars have observed that the opposite has happened, and instead many view the past 30 years as the end of the authoritative medical professional. 

With such a history of professional prominence, many have examined the observed decline in depth, and the change is largely seen as a consequence of a loss of trust with the medical profession as a whole that began some time around the late 1970’s (Timmermans and Oh 2010). During the ‘golden age’, public surveys reported extremely high levels of trust in physicians, however this declined from 72 percent in 1966 to 37 percent in 1981 (Lipset and Schneider 1982). With high levels of doubt towards medical professionals, suspicion grew about physicians acting in patients’ best interests (Reeder 1972) and patients began to question the validity of the medical doctor as an authoritative figure of biological truth. 

These shifts in the medical profession occurred parallel to changing norms surrounding the role of the patient in their own health care, and the last 30 years of scholarly research have seen a reconfiguration of the patient from passive recipient of care from their doctor to a critical consumer of health services (Barker 2008; Lupton, Donaldson, and Lloyd 1991; Timmermans and Oh 2010). Theories of medical consumerism developed from economists studying the healthcare sector, and they begin with a similar hypothesis as the economic rational choice model, assuming that patients act as rational actors in the context of a medical encounter (Timmermans and Oh 2010). In other words, individuals act in a calculated manner to engage in self-improvement or health, and they are generally skeptical about expert knowledge (Lupton 1997). According to the literature, this trend began to express itself in the form of solicitation of second opinions and a sense of interchangeability of medical practitioners during the 1980’s, just as distrust of the industry reached its peak (Gray 1997). The idea that patients could shop around and compare services and prices was heavily popularized, and patients increasingly began to make autonomous decisions when selecting physicians (Hibbard and Weeks 1987, Lupton 1991).

Urgent care centers fit neatly into such a conceptualization of health services, and thus offer a key area of analysis in better understanding the developing roles of the consumer-patient within the larger healthcare industry. An important aspect of the research on the developing patient-consumers emphasizes the expansion of bargaining power on the part of the patient that came with the shift (Reeder 1972). A patient may now shop around the marketplace of health care, and that many are now choosing urgent care centers is undeniable given the industry’s rapid expansion. 

###What does this mean for health care?{.unnumbered}

In light of such research, sociologists and those who study at the intersection of health and social behaviors have begun to re-examine the importance of a close relationship between doctor and patient in an attempt to respond to the consumer-patient model, developing a growing body of research which seeks to define the most effective components of patient-physician interactions and to reaffirm the place of the primary care physician in modern medicine. Common to most of these studies are the elements of ‘trust, compassion, communication, and clinical competence’ (Heritage and Maynard 2006; Phillips and Bazemore 2010, others at bottom). As an example, a 2002 study on clinical outcomes for low income women over the age of forty found that women who rated highest their doctor's ability to take care of all of their health care needs had 11 times the odds of ‘trusting their physician’ and 6 times the odds of finding their physicians ‘compassionate and communicative’, compared to those with the lowest level of comprehensiveness (O’Malley and Forrest 2002).

With such knowledge that close ties between physicians and patients have a direct impact on the perceived quality of care, the importance of examining the rise of urgent care centers become obvious. If patients are acting as rational consumers, which of them are choosing to receive their care outside of a primary care office, and what consequences does this have for their medical outcomes? The lack of research into the characteristics of urgent care patients make it difficult to answer such questions. Indeed, as of now, there has been no academic attempt to place the rapidly growing industry within the sociology of medicine, nor does there even exist an official definition of what constitutes an urgent care center. 


##Theories of Urgent Care usage{.unnumbered}

Urgent care centers are an obviously understudied phenomenon, and the following section applies sociological theories to better understand their role in the healthcare system. 




###Urgent Care Centers as an extension of the Welfare State{.unnumbered}

The prevailing understanding of urgent care centers interprets the industry’s growth as a development that grew out of emergency department overcrowding that began during the financial tightening of the 1980’s. Thus, each clinic is often conceptualized as a smaller instance of a traditional hospital’s triage center, supplying many services which one could receive at an emergency department (Anon n.d.; Mehrotra et al. 2008; Rubin 2012). One study which compared emergency department services with urgent care centers found that, for all but the most extreme care and emergent care needs, urgent care centers could handle almost all of emergency department traffic and that their services were remarkably analogous (Anon n.d.). Similarly, the unique features of emergency departments which set them apart from more traditional avenues of care such as the promise to be seen regardless of insurance coverage and the flexible hours are mirrored in most urgent care centers (Weinick and Betancourt n.d.). 

Given these similarities, urgent care could in many ways be considered a response by the healthcare industry to emergency department overuse, which continue to struggle underneath a lack of resources. Suitably, the body of sociological research on emergency departments can be used to better comprehend how urgent care centers are impacting the allocation of healthcare. Many medical sociologists have analyzed the public/private divide in the healthcare industry, emphasizing the unequal quality of care received depending upon which type of health service you utilize (Dutton 1978; Luftey and Freese 2005). In response to these inequalities in the private sector, the emergency room has long been understood as a response to a stratified system, and it is largely considered a social welfare institution (Gordon 1999). “The hospital emergency department is perhaps the only local institution where professional help is mandated by law, with guaranteed availability for all persons, all the time, regardless of the problem” (Ullman, Block, and Stratmann n.d.), and was for a long time widely considered one of the few access points into the healthcare system for very low income individuals. 

Accordingly, because urgent care centers offer a similar alternative to primary care for those who cannot procure a conventional family practitioner, they can be considered an extension of a much needed welfare institution necessary to circumvent an extremely stratified healthcare industry. This becomes more credible when trends in urgent care centers are examined in conjunction with emergency departments. By all indications, the demand for emergency departments far outweighs their capacity, and this is only expected to grow in the future (Weinick 2010). Around the time that urgent care centers began to emerge in the U.S., emergency departments were seeing record breaking levels of non-acute visits, resulting in severe overcrowding and shortages (Shortcliffe). These numbers have only risen in the past 20 years, especially in urban areas with large populations of low-income residents (Anon n.d.). Not only does this rise in demand correspond to the growth of the urgent care industry, one economic analysis which took cities with comparably high levels of non-emergent ED usage and examined the effect of a growing number of urgent care centers found that cities which have seen a large growth in these facilities have statistically lower overcrowding in emergency departments (O’Malley 2013). 

Thus, urgent care centers usage would be expected to closely resemble that of the emergency department, especially regarding non-emergent care. This leads to the first hypothesis which will be tested by current data on urgent care center usage. Emergency department usage has been studied by many medical professions and sociologists, with a particular focus on the ways in which it serves as a welfare institution, and a few central patterns will be used here in the comparison with urgent care centers. Primarily, the low average income of patients and high levels of uninsured visits to emergency department patients have been a steady trend in the last 30 years (Ullman et al. n.d.). Patterns of use for emergency departments also show low levels of ‘returns’ (individuals who come back with the same problem) and higher traffic during hours when normal primary care physician offices are closed, such as late at night and on the weekend (Anon n.d.; O’Malley 2013; Ullman et al. n.d.). Accordingly, if like emergency departments, urgent care centers act as a a welfare institution for those who cannot procure a traditional primary care physician, we would expect to see similar trends as have been observed in hospital emergency departments. These are summarized in Hypothesis 1 below. 

##### Hypothesis 1:  Urgent care centers will experience high levels of visits from uninsured and low SES patients, have low rates of second visits, and higher rates of visits during non-traditional hours (weekends). 

###Urgent Care Centers as a New Model of Primary Care {.unnumbered}

Yet another understanding of urgent care centers arises when one considers the larger institutional context within which the overuse of emergency departments and the boom in the urgent care industry occurred. According to medical and organizational sociologists, the institutional narrative of the American healthcare industry since the 1980’s is one of privatization and the transfer of power from professionals and the government towards the private sector and market control (Waitzkin 2000). Urgent Care centers thus fall into a rapidly expanding category of new, privately funded modes of healthcare services—other examples being retail clinics, private hospitals and home care organizations—which are provided and predominantly paid for by private actors (Anon n.d.).

This framework has yet to be fully examined by scholars, but a few studies which have attempted to examine the place of urgent care centers in new healthcare markets have pointed towards such change as being highly indicative of larger changes to healthcare, highlighting the privatization phenomenon as a possible explanation in the rise in numbers of such clinics over the last two decades or so (Rubin 2012; Weinick, Bristol, and DesRoches 2009; Yee et al. 2013). Shortages in public hospital staffing and facilities and the rising cost of care in the U.S. are seen as having created both demand and an opening for a new market within healthcare, which has been filled by new forms of medical service (Weinick and Betancourt n.d.).  And while the trend towards privatization has been seen at times as both a symptom of the loss of professional dominance by medical practitioners and the cause of it, the similarities in organizational structure to primary care practices cast doubt on the hypothesis that these new forms of care are simply emergency department overflow. As one analysis observed: “while urgent care reflects some similarities to emergency departments, we find that in other areas – most notably reimbursements, primary payer distribution, and physicians' salaries – urgent care centers seem far more similar to office-based family medicine practices” (Weinick and Bristol 2008).

Such observations lead one to a different conclusion about urgent care than those who liken the clinics to smaller triage centers created to handle emergency department overflow. Instead, urgent care centers can be conceptualized as a move by the healthcare industry towards deeper privatization, and possibly a response to medical professional authority in jeopardy. When medical sociologists first began pointing to “the end of the golden era of doctoring,” Stefan Timmermans responded by pointing to the long history of adaptability by the medical profession, which has managed to transform itself before in the wake of institutional change many times before (Timmermans, Whooley). 

Consequently, if the privatization of healthcare proves to be the primary explanation of why urgent care centers are beginning to dominate the acute-care market, one would expect to see trends in use mirror those of traditional primary care physicians rather than emergency departments. Historically, primary care often acted as a first contact point for insured patients for any acute, non-emergent health concerns of these individuals (Jost 2003). While many primary care offices will accept at least a small number of Medicaid and Medicare payments, they often have a large patient base of privately insured, financially well-off individuals (Cunningham et al. 1999). Such offices are often only open during a standard work week’s hours, a facet often noted as functioning to limit access for those who cannot take off work to go to the doctor. Lastly, primary care is often set apart from other forms of care due to the relationship and medical history that develops between the doctor and patient over years of care exchange (Miller et al. 2010). Primary care physicians thus emphasize holistic view of health care, and for those patients that do have a primary doctor, they are encouraged to return to the same clinic. If urgent care facilities are to be understood as a new face on a conventional sector of the health services industry, we should expect to see this last factor of primary care present in those going to urgent care centers. These usage trends are summarized in Hypothesis 2 below:

#####Hypothesis 2:  Urgent care centers will experience high levels of visits from insured patients across SES statuses, have high rates of second visits, and will not have significantly higher rates of visits on weekends.

###Urgent Care Centers: Emergency Rooms for the Wealthy?{.unnumbered}

An alternative explanation for the rise of urgent care use combines both of the previous theories by conceptualizing the urgent care center as an occurrence of boundary work by upper middle class and wealthy Americans who have been pushed out of emergency departments by low SES patients. Sociologists have long been interested in the ways that class can be defined and reconstituted through boundary work (Pachucki, Pendergrass, and Lamont 2007).  Research on symbolic boundaries—the conceptual distinctions made by social actors in categorizing people, practices, tastes, attitudes and manners—and their interactions with more durable and institutionalized social differences such as class and race has shown that individuals often use methods of exclusion through organizational settings in order to solidify social boundaries Zietsma and Lawrence 2010.
	
Thus, if it is true that urgent care centers are largely operationally analogous to emergency departments as is often observed, it could be that such organizations serve as an alternative for wealthy individuals who seek to socially distance themselves from a space largely inhabited by low SES patients. Such a hypothesis would explain why the industry’s rapid growth coincides with a remarkable strain on emergency departments’ capacities due to an influx of low SES patients. This explanation also accounts for the fact that urgent care centers are often more expensive due to their pay-per-service model than emergency departments (Anon n.d., Anon n.d.; Ullman et al. n.d., n.d.). Lastly, this theory offers an explanation as to why urgent care centers have developed along side of, and with many of the same services as, emergency departments Weinick et al. 2009.

If this hypothesis were the case, one would expect to observe usage trends much like Hypothesis 1, but with key differences. Primarily, regardless of insurance coverage, we should expect to see little to no low-SES users in such clinics. We would also expect to see patterns of use by the wealthy to mimic their would-be use of emergency departments, such as high volumes of visits during times when their primary care physicians are closed, emergency and injury related visits and almost no return visits. 

#####Hypothesis 3:  Urgent care centers will experience high levels of visits from high SES patients, have low rates of second visits and will have large proportions of visits which qualify as acute and emergent care during non-primary care hours.

If such trends were observed, the urgent care center could then be understood as analogous to an emergency department for the wealthy. 




