---
output: word_document
---
# Theories of Urgent Care Use {.unnumbered}
\onehalfspacing

As stated, urgent care centers are an obviously understudied phenomenon, and the following section applies the sociological theories discussed in the last chapter to better understand their role in the healthcare system. The conceptualization of urgent care as a new source of primary care for patients is contrasted against two other theories of urgent care center usage. The first applies theory to the widely matriculated explanation of urgent care by the media and health economists: that urgent care is a response to unavailability in primary care, developing out of consumer demand for quick and cost-efficient care. The second draws from the sociological research that focused on emergency departments (an oft cited cousin of urgent care centers), and explores the possibility that the industry has developed as a response to overcrowding and overuse of emergency departments in the past 20 years.

##Urgent Care Centers as an extension of the Welfare State{.unnumbered}

The prevailing understanding of urgent care centers interprets the industry’s growth as a development that grew out of emergency department overcrowding that began during the financial tightening of the 1980’s. Thus, each clinic is often conceptualized as a smaller instance of a traditional hospital’s triage center, supplying many services which one could receive at an emergency department (Anon n.d.; Mehrotra et al. 2008; Rubin 2012). One study which compared emergency department services with urgent care centers found that, for all but the most extreme care and emergent care needs, urgent care centers could handle almost all of emergency department traffic and that their services were remarkably analogous (Anon n.d.). Similarly, the unique features of emergency departments which set them apart from more traditional avenues of care such as the promise to be seen regardless of insurance coverage and the flexible hours are mirrored in most urgent care centers (Weinick and Betancourt n.d.). 

Given these similarities, urgent care could in many ways be considered a response by the healthcare industry to emergency department overuse, which continue to struggle underneath a lack of resources. Suitably, the body of sociological research on emergency departments can be used to better comprehend how urgent care centers are impacting the allocation of healthcare. Many medical sociologists have analyzed the public/private divide in the healthcare industry, emphasizing the unequal quality of care received depending upon which type of health service you utilize (Dutton 1978; Luftey and Freese 2005). In response to these inequalities in the private sector, the emergency room has long been understood as a response to a stratified system, and it is largely considered a social welfare institution (Gordon 1999). “The hospital emergency department is perhaps the only local institution where professional help is mandated by law, with guaranteed availability for all persons, all the time, regardless of the problem” (Ullman, Block, and Stratmann n.d.), and was for a long time widely considered one of the few access points into the healthcare system for very low income individuals. 

Accordingly, because urgent care centers offer a similar alternative to primary care for those who cannot procure a conventional family practitioner, they can be considered an extension of a much needed welfare institution necessary to circumvent an extremely stratified healthcare industry. This becomes more credible when trends in urgent care centers are examined in conjunction with emergency departments. By all indications, the demand for emergency departments far outweighs their capacity, and this is only expected to grow in the future (Weinick 2010). Around the time that urgent care centers began to emerge in the U.S., emergency departments were seeing record breaking levels of non-acute visits, resulting in severe overcrowding and shortages (Shortcliffe). These numbers have only risen in the past 20 years, especially in urban areas with large populations of low-income residents (Anon n.d.). Not only does this rise in demand correspond to the growth of the urgent care industry, one economic analysis which took cities with comparably high levels of non-emergent ED usage and examined the effect of a growing number of urgent care centers found that cities which have seen a large growth in these facilities have statistically lower overcrowding in emergency departments (O’Malley 2013). 

Thus, urgent care centers usage would be expected to closely resemble that of the emergency department, especially regarding non-emergent care. This leads to the first hypothesis which will be tested by current data on urgent care center usage. Emergency department usage has been studied by many medical professions and sociologists, with a particular focus on the ways in which it serves as a welfare institution, and a few central patterns will be used here in the comparison with urgent care centers. Primarily, the low average income of patients and high levels of uninsured visits to emergency department patients have been a steady trend in the last 30 years (Ullman et al. n.d.). Patterns of use for emergency departments also show low levels of ‘returns’ (individuals who come back with the same problem) and higher traffic during hours when normal primary care physician offices are closed, such as late at night and on the weekend (Anon n.d.; O’Malley 2013; Ullman et al. n.d.). Accordingly, if like emergency departments, urgent care centers act as a a welfare institution for those who cannot procure a traditional primary care physician, we would expect to see similar trends as have been observed in hospital emergency departments. These are summarized in Hypothesis 1 below. 

##### Hypothesis 1:  Urgent care centers will experience high levels of visits from uninsured and low SES patients, have low rates of second visits, and higher rates of visits during non-traditional hours (weekends). 


##Urgent Care Centers: Emergency Rooms for the Wealthy?{.unnumbered}

An alternative explanation for the rise of urgent care use combines both of the previous theories by conceptualizing the urgent care center as an occurrence of boundary work by upper middle class and wealthy Americans who have been pushed out of emergency departments by low SES patients. Sociologists have long been interested in the ways that class can be defined and reconstituted through boundary work (Pachucki, Pendergrass, and Lamont 2007).  Research on symbolic boundaries—the conceptual distinctions made by social actors in categorizing people, practices, tastes, attitudes and manners—and their interactions with more durable and institutionalized social differences such as class and race has shown that individuals often use methods of exclusion through organizational settings in order to solidify social boundaries Zietsma and Lawrence 2010.
	
Thus, if it is true that urgent care centers are largely operationally analogous to emergency departments as is often observed, it could be that such organizations serve as an alternative for wealthy individuals who seek to socially distance themselves from a space largely inhabited by low SES patients. Such a hypothesis would explain why the industry’s rapid growth coincides with a remarkable strain on emergency departments’ capacities due to an influx of low SES patients. This explanation also accounts for the fact that urgent care centers are often more expensive due to their pay-per-service model than emergency departments (Anon n.d., Anon n.d.; Ullman et al. n.d., n.d.). Lastly, this theory offers an explanation as to why urgent care centers have developed along side of, and with many of the same services as, emergency departments Weinick et al. 2009.

If this hypothesis were the case, one would expect to observe usage trends much like Hypothesis 1, but with key differences. Primarily, regardless of insurance coverage, we should expect to see little to no low-SES users in such clinics. We would also expect to see patterns of use by the wealthy to mimic their would-be use of emergency departments, such as high volumes of visits during times when their primary care physicians are closed, emergency and injury related visits and almost no return visits. 

##### Hypothesis 3:  Urgent care centers will experience high levels of visits from high SES patients, have low rates of second visits and will have large proportions of visits which qualify as acute and emergent care during non-primary care hours.


##Urgent Care Centers as a New Model of Primary Care {.unnumbered}

Yet another understanding of urgent care centers arises when one considers the larger institutional context within which the overuse of emergency departments and the boom in the urgent care industry occurred. According to medical and organizational sociologists, the institutional narrative of the American healthcare industry since the 1980’s is one of privatization and the transfer of power from professionals and the government towards the private sector and market control (Waitzkin 2000). Urgent Care centers thus fall into a rapidly expanding category of new, privately funded modes of healthcare services—other examples being retail clinics, private hospitals and home care organizations—which are provided and predominantly paid for by private actors (Anon n.d.).

This framework has yet to be fully examined by scholars, but a few studies which have attempted to examine the place of urgent care centers in new healthcare markets have pointed towards such change as being highly indicative of larger changes to healthcare, highlighting the privatization phenomenon as a possible explanation in the rise in numbers of such clinics over the last two decades or so (Rubin 2012; Weinick, Bristol, and DesRoches 2009; Yee et al. 2013). Shortages in public hospital staffing and facilities and the rising cost of care in the U.S. are seen as having created both demand and an opening for a new market within healthcare, which has been filled by new forms of medical service (Weinick and Betancourt n.d.).  And while the trend towards privatization has been seen at times as both a symptom of the loss of professional dominance by medical practitioners and the cause of it, the similarities in organizational structure to primary care practices cast doubt on the hypothesis that these new forms of care are simply emergency department overflow. As one analysis observed: “while urgent care reflects some similarities to emergency departments, we find that in other areas – most notably reimbursements, primary payer distribution, and physicians' salaries – urgent care centers seem far more similar to office-based family medicine practices” (Weinick and Bristol 2008).

Such observations lead one to a different conclusion about urgent care than those who liken the clinics to smaller triage centers created to handle emergency department overflow. Instead, urgent care centers can be conceptualized as a move by the healthcare industry towards deeper privatization, and possibly a response to medical professional authority in jeopardy. When medical sociologists first began pointing to “the end of the golden era of doctoring,” Stefan Timmermans responded by pointing to the long history of adaptability by the medical profession, which has managed to transform itself before in the wake of institutional change many times before (Timmermans, Whooley). 

Consequently, if the privatization of healthcare proves to be the primary explanation of why urgent care centers are beginning to dominate the acute-care market, one would expect to see trends in use mirror those of traditional primary care physicians rather than emergency departments. Historically, primary care often acted as a first contact point for insured patients for any acute, non-emergent health concerns of these individuals (Jost 2003). While many primary care offices will accept at least a small number of Medicaid and Medicare payments, they often have a large patient base of privately insured, financially well-off individuals (Cunningham et al. 1999). Such offices are often only open during a standard work week’s hours, a facet often noted as functioning to limit access for those who cannot take off work to go to the doctor. Lastly, primary care is often set apart from other forms of care due to the relationship and medical history that develops between the doctor and patient over years of care exchange (Miller et al. 2010). Primary care physicians thus emphasize holistic view of health care, and for those patients that do have a primary doctor, they are encouraged to return to the same clinic. If urgent care facilities are to be understood as a new face on a conventional sector of the health services industry, we should expect to see this last factor of primary care present in those going to urgent care centers. These usage trends are summarized in Hypothesis 2 below:

##### Hypothesis 2:  Urgent care centers will experience high levels of visits from insured patients across SES statuses, have high rates of second visits, and will not have significantly higher rates of visits on weekends.

##Urgent Care Centers as a New Model of Primary Care {.unnumbered}

Yet another understanding of urgent care centers arises when one considers the larger institutional context within which the overuse of emergency departments and the boom in the urgent care industry occurred. According to medical and organizational sociologists, the institutional narrative of the American healthcare industry since the 1980’s is one of privatization and the transfer of power from professionals and the government towards the private sector and market control (Waitzkin 2000). Urgent Care centers thus fall into a rapidly expanding category of new, privately funded modes of healthcare services—other examples being retail clinics, private hospitals and home care organizations—which are provided and predominantly paid for by private actors (Anon n.d.).

This framework has yet to be fully examined by scholars, but a few studies which have attempted to examine the place of urgent care centers in new healthcare markets have pointed towards such change as being highly indicative of larger changes to healthcare, highlighting the privatization phenomenon as a possible explanation in the rise in numbers of such clinics over the last two decades or so (Rubin 2012; Weinick, Bristol, and DesRoches 2009; Yee et al. 2013). Shortages in public hospital staffing and facilities and the rising cost of care in the U.S. are seen as having created both demand and an opening for a new market within healthcare, which has been filled by new forms of medical service (Weinick and Betancourt n.d.).  And while the trend towards privatization has been seen at times as both a symptom of the loss of professional dominance by medical practitioners and the cause of it, the similarities in organizational structure to primary care practices cast doubt on the hypothesis that these new forms of care are simply emergency department overflow. As one analysis observed: “while urgent care reflects some similarities to emergency departments, we find that in other areas – most notably reimbursements, primary payer distribution, and physicians' salaries – urgent care centers seem far more similar to office-based family medicine practices” (Weinick and Bristol 2008).

Such observations lead one to a different conclusion about urgent care than those who liken the clinics to smaller triage centers created to handle emergency department overflow. Instead, urgent care centers can be conceptualized as a move by the healthcare industry towards deeper privatization, and possibly a response to medical professional authority in jeopardy. When medical sociologists first began pointing to “the end of the golden era of doctoring,” Stefan Timmermans responded by pointing to the long history of adaptability by the medical profession, which has managed to transform itself before in the wake of institutional change many times before (Timmermans, Whooley). 

Consequently, if the privatization of healthcare proves to be the primary explanation of why urgent care centers are beginning to dominate the acute-care market, one would expect to see trends in use mirror those of traditional primary care physicians rather than emergency departments. Historically, primary care often acted as a first contact point for insured patients for any acute, non-emergent health concerns of these individuals (Jost 2003). While many primary care offices will accept at least a small number of Medicaid and Medicare payments, they often have a large patient base of privately insured, financially well-off individuals (Cunningham et al. 1999). Such offices are often only open during a standard work week’s hours, a facet often noted as functioning to limit access for those who cannot take off work to go to the doctor. Lastly, primary care is often set apart from other forms of care due to the relationship and medical history that develops between the doctor and patient over years of care exchange (Miller et al. 2010). Primary care physicians thus emphasize holistic view of health care, and for those patients that do have a primary doctor, they are encouraged to return to the same clinic. If urgent care facilities are to be understood as a new face on a conventional sector of the health services industry, we should expect to see this last factor of primary care present in those going to urgent care centers. These usage trends are summarized in Hypothesis 2 below:

##### Hypothesis 2:  Urgent care centers will experience high levels of visits from insured patients across SES statuses, have high rates of second visits, and will not have significantly higher rates of visits on weekends.




If such trends were observed, the urgent care center could then be understood as analogous to an emergency department for the wealthy. 
