---
author: 'Kaitlyn R. Jackson'
date: 'May 2016'
division: 'History and Social Sciences'
advisor: 'Jessica Epstein'
department: 'Sociology'
title: 'New choices in primary care: A statistical analysis of urgent care patients'
abstract: >
   \doublespacing Urgent care centers are a relatively new and emergent phenomemnon in the American health care system, yet little to no academic reasearch has been performed on how they are situated in the larger sociological understanding of the healthcare system. This thesis attempts to further such an understanding by examining the typologies of patients which are the users of urgent care, and further, who of those uses such centers as their primary care physicians.
acknowledgements: >
  \doublespacing I want to thank all of my friends and family who have cheered me on from the sidelines for the past four years. I couldn't have made it through my sophomore year, no less this thesis without you guys. Thanks also to the professors I've had at Reed. I've come out of this place a different person than when I came in, and I don't think any acknowledgment would be enough thanks.
dedication: >
  To my family, both those I came with and those I found at Reed.
#preface: >
#  This is an example of a thesis setup to use the reed thesis document class.
bibliography: bib/THESIS.bib
# Download your specific bibliography database file and refer to it in the line above.
csl: csl/american-sociological-association.csl
# Download your specific csl file and refer to it in the line above.
output: 
  reedtemplates::reed_thesis:
    toc: true
    toc_depth: 2
lot: true
lof: true
#space_between_paragraphs: true
header-includes:
  \usepackage{tikz}
  \usepackage{setspace}
  \usepackage{amsmath}
  \usepackage{natbib}
  \usepackage{rotating}
  \usepackage{longtable}
  \usepackage{booktabs}
  \pagestyle{plain}
---


```{r include_rticles, include = FALSE, warning=FALSE, message=FALSE  ,echo=FALSE}
# This chunk ensures that the rticles package is installed and loaded
# This rticles package includes the template files for the thesis and also
# two functions used for labeling and referencing
if(!require(devtools))
  install.packages("devtools", repos = "http://cran.rstudio.com")
if(!require(reedtemplates)){
  library(devtools)
  devtools::install_github("ismayc/reedtemplates")
  }
library(reedtemplates)
```

<!--
This is the way to split your thesis into chapters and then include each of the chapters seperately.  You can Knit the Rmd files corresponding to each chapter individually and then put them all back together by Knit-ing this document.
-->


```{r chapter0, child = 'Intro.Rmd'}
```

```{r chapter1, child = 'Lit_Review.Rmd'}
```

```{r chapter2, child = 'theory.Rmd'}
```

```{r chapter3, child = 'Methods.Rmd'}
```

```{r chapter4, child = 'Analysis.Rmd'}
```

```{r chapter5, child = 'conclusion.Rmd'}
```

```{r chapter6, child = 'appendix2.Rmd'}
```

```{r chapter7, child = 'appendix1.Rmd'}
```


<!--
The bib chunk below must go last in this document according to how R Markdown renders.  More info is at http://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html
-->

```{r bib, child = 'Biblio.Rmd'}
```




